variant = "loose"

[[issues]]
file = "src/WaffleRuntime.php"
code = "non-existent-method"
message = 'Method `reset` does not exist on type `Waffle\Commons\Contracts\Core\KernelInterface`.'
count = 1

[[issues]]
file = "tests/src/WaffleRuntimeTest.php"
code = "property-type-coercion"
message = 'A value of a less specific type `Psr\Http\Message\ServerRequestInterface&PHPUnit\Framework\MockObject\Stub` is being assigned to property `$$request` (Psr\Http\Message\ServerRequestInterface&PHPUnit\Framework\MockObject\MockObject).'
count = 1

[[issues]]
file = "tests/src/WaffleRuntimeTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\Runtime\WaffleRuntimeTest::setUp`.'
count = 1

[[issues]]
file = "tests/src/WaffleRuntimeTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\Runtime\WaffleRuntimeTest::testLoopOrchestratesRequestLifecycleCorrectly`.'
count = 1

[[issues]]
file = "tests/src/WaffleRuntimeTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\Runtime\WaffleRuntimeTest::setUp`.'
count = 1

[[issues]]
file = "tests/src/WaffleRuntimeTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\Runtime\WaffleRuntimeTest::testLoopOrchestratesRequestLifecycleCorrectly`.'
count = 1

[[issues]]
file = "tests/src/WaffleRuntimeTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\Runtime\WaffleRuntimeTest::setUp`.'
count = 1

[[issues]]
file = "tests/src/WaffleRuntimeTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\Runtime\WaffleRuntimeTest::testLoopOrchestratesRequestLifecycleCorrectly`.'
count = 1
