[[entries."tests/src/AbstractTestCase.php".issues]]
code = "no-redundant-method-override"
start_line = 10
end_line = 14

[[entries."tests/src/AbstractTestCase.php".issues]]
code = "no-redundant-method-override"
start_line = 16
end_line = 20

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "assertion-style"
start_line = 53
end_line = 53

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "assertion-style"
start_line = 60
end_line = 60
