[[entries."tests/src/AbstractTestCase.php".issues]]
code = "no-redundant-method-override"
start_line = 10
end_line = 14

[[entries."tests/src/AbstractTestCase.php".issues]]
code = "no-redundant-method-override"
start_line = 16
end_line = 20

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "assertion-style"
start_line = 31
end_line = 31

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "no-redundant-use"
start_line = 6
end_line = 6

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "no-redundant-use"
start_line = 8
end_line = 8

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "no-redundant-use"
start_line = 9
end_line = 9
