[[entries."src/WaffleRuntime.php".issues]]
code = "non-existent-class-like"
start_line = 21
end_line = 21

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "invalid-argument"
start_line = 63
end_line = 63

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "invalid-method-access"
start_line = 51
end_line = 51

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "invalid-method-access"
start_line = 58
end_line = 58

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "invalid-property-assignment-value"
start_line = 34
end_line = 34

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "invalid-property-assignment-value"
start_line = 36
end_line = 36

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "missing-override-attribute"
start_line = 29
end_line = 29

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "mixed-method-access"
start_line = 52
end_line = 52

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "mixed-method-access"
start_line = 53
end_line = 53

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "mixed-method-access"
start_line = 54
end_line = 54

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "mixed-method-access"
start_line = 59
end_line = 59

[[entries."tests/src/WaffleRuntimeTest.php".issues]]
code = "mixed-method-access"
start_line = 60
end_line = 60
