variant = "loose"

[[issues]]
file = "tests/src/AbstractTestCase.php"
code = "no-redundant-method-override"
message = "Redundant method override."
count = 2

[[issues]]
file = "tests/src/WaffleRuntimeTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 2
